# Generated by Django 2.1.5 on 2021-05-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='summary',
            new_name='emp_status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='mar_status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
