# Generated by Django 2.1.5 on 2021-05-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210512_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='employement_status',
            new_name='employment_status',
        ),
    ]
