# Generated by Django 2.1.5 on 2021-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210512_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='age',
            new_name='dependants',
        ),
        migrations.AddField(
            model_name='product',
            name='graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
