# Generated by Django 2.1.5 on 2021-05-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210512_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('sex', models.TextField(default=' ')),
                ('DOB', models.DateField()),
                ('phone_number', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
