# Generated by Django 2.1.5 on 2021-05-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='DOB',
            field=models.DateField(auto_now=True),
        ),
    ]
