# Generated by Django 2.1.5 on 2021-06-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210604_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='graduate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='married',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='self_employed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='semi_urban',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='urban',
            field=models.IntegerField(default=0),
        ),
    ]
