# Generated by Django 2.1.5 on 2021-06-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210607_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='loan_amount',
            field=models.IntegerField(default=0),
        ),
    ]
