# Generated by Django 2.1.5 on 2021-06-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210625_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='graduate',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='married',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='self_employed',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='semi_urban',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='urban',
            field=models.TextField(default=0),
        ),
    ]
